package com.ngs.model;
// Generated 18-Oct-2017 09:46:59 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Systems generated by hbm2java
 */
public class Systems  implements java.io.Serializable {


     private Integer id;
     private Branch branch;
     private Brand brand;
     private Company company;
     private String name;
     private String model;
     private String systemNo;
     private String description;
     private String configType;
     private Integer status;
     private String lon;
     private String lat;
     private String url;
     private String ip;
     private Date regtime;
     private String spare1;
     private String spare2;
     private Set<Alarm> alarms = new HashSet<Alarm>(0);
     private Set<Tt> tts = new HashSet<Tt>(0);
     private Set<Heartbeat> heartbeats = new HashSet<Heartbeat>(0);
     private Set<SystemsHasUser> systemsHasUsers = new HashSet<SystemsHasUser>(0);
     private Set<Request> requests = new HashSet<Request>(0);
     private Set<SystemsHasParameters> systemsHasParameterses = new HashSet<SystemsHasParameters>(0);

    public Systems() {
    }

	
    public Systems(Company company) {
        this.company = company;
    }
    public Systems(Branch branch, Brand brand, Company company, String name, String model, String systemNo, String description, String configType, Integer status, String lon, String lat, String url, String ip, Date regtime, String spare1, String spare2, Set<Alarm> alarms, Set<Tt> tts, Set<Heartbeat> heartbeats, Set<SystemsHasUser> systemsHasUsers, Set<Request> requests, Set<SystemsHasParameters> systemsHasParameterses) {
       this.branch = branch;
       this.brand = brand;
       this.company = company;
       this.name = name;
       this.model = model;
       this.systemNo = systemNo;
       this.description = description;
       this.configType = configType;
       this.status = status;
       this.lon = lon;
       this.lat = lat;
       this.url = url;
       this.ip = ip;
       this.regtime = regtime;
       this.spare1 = spare1;
       this.spare2 = spare2;
       this.alarms = alarms;
       this.tts = tts;
       this.heartbeats = heartbeats;
       this.systemsHasUsers = systemsHasUsers;
       this.requests = requests;
       this.systemsHasParameterses = systemsHasParameterses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Branch getBranch() {
        return this.branch;
    }
    
    public void setBranch(Branch branch) {
        this.branch = branch;
    }
    public Brand getBrand() {
        return this.brand;
    }
    
    public void setBrand(Brand brand) {
        this.brand = brand;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public String getSystemNo() {
        return this.systemNo;
    }
    
    public void setSystemNo(String systemNo) {
        this.systemNo = systemNo;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getConfigType() {
        return this.configType;
    }
    
    public void setConfigType(String configType) {
        this.configType = configType;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getLon() {
        return this.lon;
    }
    
    public void setLon(String lon) {
        this.lon = lon;
    }
    public String getLat() {
        return this.lat;
    }
    
    public void setLat(String lat) {
        this.lat = lat;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public Date getRegtime() {
        return this.regtime;
    }
    
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }
    public String getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(String spare1) {
        this.spare1 = spare1;
    }
    public String getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(String spare2) {
        this.spare2 = spare2;
    }
    public Set<Alarm> getAlarms() {
        return this.alarms;
    }
    
    public void setAlarms(Set<Alarm> alarms) {
        this.alarms = alarms;
    }
    public Set<Tt> getTts() {
        return this.tts;
    }
    
    public void setTts(Set<Tt> tts) {
        this.tts = tts;
    }
    public Set<Heartbeat> getHeartbeats() {
        return this.heartbeats;
    }
    
    public void setHeartbeats(Set<Heartbeat> heartbeats) {
        this.heartbeats = heartbeats;
    }
    public Set<SystemsHasUser> getSystemsHasUsers() {
        return this.systemsHasUsers;
    }
    
    public void setSystemsHasUsers(Set<SystemsHasUser> systemsHasUsers) {
        this.systemsHasUsers = systemsHasUsers;
    }
    public Set<Request> getRequests() {
        return this.requests;
    }
    
    public void setRequests(Set<Request> requests) {
        this.requests = requests;
    }
    public Set<SystemsHasParameters> getSystemsHasParameterses() {
        return this.systemsHasParameterses;
    }
    
    public void setSystemsHasParameterses(Set<SystemsHasParameters> systemsHasParameterses) {
        this.systemsHasParameterses = systemsHasParameterses;
    }




}


