package com.ngs.model;
// Generated 28-Jul-2017 12:19:42 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Activities generated by hbm2java
 */
public class Activities  implements java.io.Serializable {


     private Integer id;
     private Category category;
     private String activitiy;
     private Integer status;
     private String description;
     private String url;
     private Integer order;
     private Set<RollHasActivities> rollHasActivitieses = new HashSet<RollHasActivities>(0);

    public Activities() {
    }

	
    public Activities(Category category) {
        this.category = category;
    }
    public Activities(Category category, String activitiy, Integer status, String description, String url, Integer order, Set<RollHasActivities> rollHasActivitieses) {
       this.category = category;
       this.activitiy = activitiy;
       this.status = status;
       this.description = description;
       this.url = url;
       this.order = order;
       this.rollHasActivitieses = rollHasActivitieses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getActivitiy() {
        return this.activitiy;
    }
    
    public void setActivitiy(String activitiy) {
        this.activitiy = activitiy;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Integer getOrder() {
        return this.order;
    }
    
    public void setOrder(Integer order) {
        this.order = order;
    }
    public Set<RollHasActivities> getRollHasActivitieses() {
        return this.rollHasActivitieses;
    }
    
    public void setRollHasActivitieses(Set<RollHasActivities> rollHasActivitieses) {
        this.rollHasActivitieses = rollHasActivitieses;
    }




}


