package com.ngs.model;
// Generated 28-Jul-2017 12:19:42 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String categorycol;
     private Set<Activities> activitieses = new HashSet<Activities>(0);

    public Category() {
    }

    public Category(String name, String categorycol, Set<Activities> activitieses) {
       this.name = name;
       this.categorycol = categorycol;
       this.activitieses = activitieses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCategorycol() {
        return this.categorycol;
    }
    
    public void setCategorycol(String categorycol) {
        this.categorycol = categorycol;
    }
    public Set<Activities> getActivitieses() {
        return this.activitieses;
    }
    
    public void setActivitieses(Set<Activities> activitieses) {
        this.activitieses = activitieses;
    }




}


