package com.ngs.model;
// Generated 28-Jul-2017 15:59:13 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Heartbeat generated by hbm2java
 */
public class Heartbeat  implements java.io.Serializable {


     private Integer id;
     private Systems systems;
     private String ip;
     private String description;
     private Date regtime;
     private Integer status;

    public Heartbeat() {
    }

	
    public Heartbeat(Systems systems) {
        this.systems = systems;
    }
    public Heartbeat(Systems systems, String ip, String description, Date regtime, Integer status) {
       this.systems = systems;
       this.ip = ip;
       this.description = description;
       this.regtime = regtime;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Systems getSystems() {
        return this.systems;
    }
    
    public void setSystems(Systems systems) {
        this.systems = systems;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getRegtime() {
        return this.regtime;
    }
    
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


