package com.ngs.model;
// Generated 28-Jul-2017 12:19:42 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private Integer id;
     private User user;
     private Rolls rolls;
     private String username;
     private String password;
     private Integer status;
     private Set<Log> logs = new HashSet<Log>(0);

    public Login() {
    }

	
    public Login(User user, Rolls rolls) {
        this.user = user;
        this.rolls = rolls;
    }
    public Login(User user, Rolls rolls, String username, String password, Integer status, Set<Log> logs) {
       this.user = user;
       this.rolls = rolls;
       this.username = username;
       this.password = password;
       this.status = status;
       this.logs = logs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Rolls getRolls() {
        return this.rolls;
    }
    
    public void setRolls(Rolls rolls) {
        this.rolls = rolls;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set<Log> getLogs() {
        return this.logs;
    }
    
    public void setLogs(Set<Log> logs) {
        this.logs = logs;
    }




}


