package com.ngs.model;
// Generated 28-Jul-2017 12:19:42 by Hibernate Tools 3.6.0



/**
 * RollHasActivities generated by hbm2java
 */
public class RollHasActivities  implements java.io.Serializable {


     private Integer id;
     private Rolls rolls;
     private Activities activities;
     private Integer status;

    public RollHasActivities() {
    }

	
    public RollHasActivities(Rolls rolls, Activities activities) {
        this.rolls = rolls;
        this.activities = activities;
    }
    public RollHasActivities(Rolls rolls, Activities activities, Integer status) {
       this.rolls = rolls;
       this.activities = activities;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Rolls getRolls() {
        return this.rolls;
    }
    
    public void setRolls(Rolls rolls) {
        this.rolls = rolls;
    }
    public Activities getActivities() {
        return this.activities;
    }
    
    public void setActivities(Activities activities) {
        this.activities = activities;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


