package com.ngs.model;
// Generated 28-Aug-2017 17:02:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Systems generated by hbm2java
 */
public class Systems  implements java.io.Serializable {


     private Integer id;
     private Company company;
     private String name;
     private String description;
     private Integer status;
     private String lon;
     private String lat;
     private String url;
     private String ip;
     private String spare1;
     private String spare2;
     private Set<Alarm> alarms = new HashSet<Alarm>(0);
     private Set<Tt> tts = new HashSet<Tt>(0);
     private Set<Heartbeat> heartbeats = new HashSet<Heartbeat>(0);
     private Set<SystemsHasUser> systemsHasUsers = new HashSet<SystemsHasUser>(0);
     private Set<Request> requests = new HashSet<Request>(0);
     private Set<SystemsHasParameters> systemsHasParameterses = new HashSet<SystemsHasParameters>(0);

    public Systems() {
    }

	
    public Systems(Company company) {
        this.company = company;
    }
    public Systems(Company company, String name, String description, Integer status, String lon, String lat, String url, String ip, String spare1, String spare2, Set<Alarm> alarms, Set<Tt> tts, Set<Heartbeat> heartbeats, Set<SystemsHasUser> systemsHasUsers, Set<Request> requests, Set<SystemsHasParameters> systemsHasParameterses) {
       this.company = company;
       this.name = name;
       this.description = description;
       this.status = status;
       this.lon = lon;
       this.lat = lat;
       this.url = url;
       this.ip = ip;
       this.spare1 = spare1;
       this.spare2 = spare2;
       this.alarms = alarms;
       this.tts = tts;
       this.heartbeats = heartbeats;
       this.systemsHasUsers = systemsHasUsers;
       this.requests = requests;
       this.systemsHasParameterses = systemsHasParameterses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getLon() {
        return this.lon;
    }
    
    public void setLon(String lon) {
        this.lon = lon;
    }
    public String getLat() {
        return this.lat;
    }
    
    public void setLat(String lat) {
        this.lat = lat;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public String getSpare1() {
        return this.spare1;
    }
    
    public void setSpare1(String spare1) {
        this.spare1 = spare1;
    }
    public String getSpare2() {
        return this.spare2;
    }
    
    public void setSpare2(String spare2) {
        this.spare2 = spare2;
    }
    public Set<Alarm> getAlarms() {
        return this.alarms;
    }
    
    public void setAlarms(Set<Alarm> alarms) {
        this.alarms = alarms;
    }
    public Set<Tt> getTts() {
        return this.tts;
    }
    
    public void setTts(Set<Tt> tts) {
        this.tts = tts;
    }
    public Set<Heartbeat> getHeartbeats() {
        return this.heartbeats;
    }
    
    public void setHeartbeats(Set<Heartbeat> heartbeats) {
        this.heartbeats = heartbeats;
    }
    public Set<SystemsHasUser> getSystemsHasUsers() {
        return this.systemsHasUsers;
    }
    
    public void setSystemsHasUsers(Set<SystemsHasUser> systemsHasUsers) {
        this.systemsHasUsers = systemsHasUsers;
    }
    public Set<Request> getRequests() {
        return this.requests;
    }
    
    public void setRequests(Set<Request> requests) {
        this.requests = requests;
    }
    public Set<SystemsHasParameters> getSystemsHasParameterses() {
        return this.systemsHasParameterses;
    }
    
    public void setSystemsHasParameterses(Set<SystemsHasParameters> systemsHasParameterses) {
        this.systemsHasParameterses = systemsHasParameterses;
    }




}


