package com.ngs.model;
// Generated 28-Jul-2017 12:19:42 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TtUpdate generated by hbm2java
 */
public class TtUpdate  implements java.io.Serializable {


     private Integer id;
     private User user;
     private Tt tt;
     private String comment;
     private Date regtime;
     private Integer status;
     private String info;
     private Set<Alerts> alertses = new HashSet<Alerts>(0);

    public TtUpdate() {
    }

	
    public TtUpdate(User user, Tt tt) {
        this.user = user;
        this.tt = tt;
    }
    public TtUpdate(User user, Tt tt, String comment, Date regtime, Integer status, String info, Set<Alerts> alertses) {
       this.user = user;
       this.tt = tt;
       this.comment = comment;
       this.regtime = regtime;
       this.status = status;
       this.info = info;
       this.alertses = alertses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Tt getTt() {
        return this.tt;
    }
    
    public void setTt(Tt tt) {
        this.tt = tt;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Date getRegtime() {
        return this.regtime;
    }
    
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }
    public Set<Alerts> getAlertses() {
        return this.alertses;
    }
    
    public void setAlertses(Set<Alerts> alertses) {
        this.alertses = alertses;
    }




}


