package com.ngs.model;
// Generated 13-Oct-2017 13:23:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Brand generated by hbm2java
 */
public class Brand  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private String brandNumber;
     private Date regtime;
     private Integer status;
     private Set<Systems> systemses = new HashSet<Systems>(0);

    public Brand() {
    }

    public Brand(String name, String description, String brandNumber, Date regtime, Integer status, Set<Systems> systemses) {
       this.name = name;
       this.description = description;
       this.brandNumber = brandNumber;
       this.regtime = regtime;
       this.status = status;
       this.systemses = systemses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getBrandNumber() {
        return this.brandNumber;
    }
    
    public void setBrandNumber(String brandNumber) {
        this.brandNumber = brandNumber;
    }
    public Date getRegtime() {
        return this.regtime;
    }
    
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set<Systems> getSystemses() {
        return this.systemses;
    }
    
    public void setSystemses(Set<Systems> systemses) {
        this.systemses = systemses;
    }




}


