package com.ngs.model;
// Generated 13-Oct-2017 13:23:18 by Hibernate Tools 4.3.1



/**
 * LessonLearnt generated by hbm2java
 */
public class LessonLearnt  implements java.io.Serializable {


     private Integer id;
     private Tt tt;
     private String description;
     private Integer status;

    public LessonLearnt() {
    }

	
    public LessonLearnt(Tt tt) {
        this.tt = tt;
    }
    public LessonLearnt(Tt tt, String description, Integer status) {
       this.tt = tt;
       this.description = description;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tt getTt() {
        return this.tt;
    }
    
    public void setTt(Tt tt) {
        this.tt = tt;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


