package com.ngs.model;
// Generated 13-Oct-2017 13:23:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Parameters generated by hbm2java
 */
public class Parameters  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String comment;
     private Date regtime;
     private String upperValue;
     private String lowValue;
     private String upperComment;
     private String lowerComment;
     private String unit;
     private Integer status;
     private Set<SystemsHasParameters> systemsHasParameterses = new HashSet<SystemsHasParameters>(0);
     private Set<Request> requests = new HashSet<Request>(0);

    public Parameters() {
    }

    public Parameters(String name, String comment, Date regtime, String upperValue, String lowValue, String upperComment, String lowerComment, String unit, Integer status, Set<SystemsHasParameters> systemsHasParameterses, Set<Request> requests) {
       this.name = name;
       this.comment = comment;
       this.regtime = regtime;
       this.upperValue = upperValue;
       this.lowValue = lowValue;
       this.upperComment = upperComment;
       this.lowerComment = lowerComment;
       this.unit = unit;
       this.status = status;
       this.systemsHasParameterses = systemsHasParameterses;
       this.requests = requests;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Date getRegtime() {
        return this.regtime;
    }
    
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }
    public String getUpperValue() {
        return this.upperValue;
    }
    
    public void setUpperValue(String upperValue) {
        this.upperValue = upperValue;
    }
    public String getLowValue() {
        return this.lowValue;
    }
    
    public void setLowValue(String lowValue) {
        this.lowValue = lowValue;
    }
    public String getUpperComment() {
        return this.upperComment;
    }
    
    public void setUpperComment(String upperComment) {
        this.upperComment = upperComment;
    }
    public String getLowerComment() {
        return this.lowerComment;
    }
    
    public void setLowerComment(String lowerComment) {
        this.lowerComment = lowerComment;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set<SystemsHasParameters> getSystemsHasParameterses() {
        return this.systemsHasParameterses;
    }
    
    public void setSystemsHasParameterses(Set<SystemsHasParameters> systemsHasParameterses) {
        this.systemsHasParameterses = systemsHasParameterses;
    }
    public Set<Request> getRequests() {
        return this.requests;
    }
    
    public void setRequests(Set<Request> requests) {
        this.requests = requests;
    }




}


