package com.ngs.model;
// Generated 13-Oct-2017 13:23:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rolls generated by hbm2java
 */
public class Rolls  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Integer status;
     private Set<RollHasActivities> rollHasActivitieses = new HashSet<RollHasActivities>(0);
     private Set<Login> logins = new HashSet<Login>(0);

    public Rolls() {
    }

    public Rolls(String name, Integer status, Set<RollHasActivities> rollHasActivitieses, Set<Login> logins) {
       this.name = name;
       this.status = status;
       this.rollHasActivitieses = rollHasActivitieses;
       this.logins = logins;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set<RollHasActivities> getRollHasActivitieses() {
        return this.rollHasActivitieses;
    }
    
    public void setRollHasActivitieses(Set<RollHasActivities> rollHasActivitieses) {
        this.rollHasActivitieses = rollHasActivitieses;
    }
    public Set<Login> getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set<Login> logins) {
        this.logins = logins;
    }




}


