package com.ngs.model;
// Generated 13-Oct-2017 13:23:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SystemsHasParameters generated by hbm2java
 */
public class SystemsHasParameters  implements java.io.Serializable {


     private Integer id;
     private Parameters parameters;
     private Systems systems;
     private Integer status;
     private Set<Periodic> periodics = new HashSet<Periodic>(0);

    public SystemsHasParameters() {
    }

	
    public SystemsHasParameters(Parameters parameters, Systems systems) {
        this.parameters = parameters;
        this.systems = systems;
    }
    public SystemsHasParameters(Parameters parameters, Systems systems, Integer status, Set<Periodic> periodics) {
       this.parameters = parameters;
       this.systems = systems;
       this.status = status;
       this.periodics = periodics;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Parameters getParameters() {
        return this.parameters;
    }
    
    public void setParameters(Parameters parameters) {
        this.parameters = parameters;
    }
    public Systems getSystems() {
        return this.systems;
    }
    
    public void setSystems(Systems systems) {
        this.systems = systems;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set<Periodic> getPeriodics() {
        return this.periodics;
    }
    
    public void setPeriodics(Set<Periodic> periodics) {
        this.periodics = periodics;
    }




}


