package model;
// Generated Aug 29, 2017 2:09:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Alarmname generated by hbm2java
 */
public class Alarmname  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String comment;
     private Integer status;
     private Set alarms = new HashSet(0);

    public Alarmname() {
    }

    public Alarmname(String name, String comment, Integer status, Set alarms) {
       this.name = name;
       this.comment = comment;
       this.status = status;
       this.alarms = alarms;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getAlarms() {
        return this.alarms;
    }
    
    public void setAlarms(Set alarms) {
        this.alarms = alarms;
    }




}


