package model;
// Generated Aug 29, 2017 2:09:57 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Alarm generated by hbm2java
 */
public class Alarm  implements java.io.Serializable {


     private Integer id;
     private Alarmname alarmname;
     private Systems systems;
     private Tt tt;
     private Types types;
     private String alarm;
     private Date regtime;
     private Integer status;
     private Integer severity;
     private String details;
     private Date originatetime;
     private Date cleartime;

    public Alarm() {
    }

	
    public Alarm(Systems systems, Types types, String alarm, Date regtime) {
        this.systems = systems;
        this.types = types;
        this.alarm = alarm;
        this.regtime = regtime;
    }
    public Alarm(Alarmname alarmname, Systems systems, Tt tt, Types types, String alarm, Date regtime, Integer status, Integer severity, String details, Date originatetime, Date cleartime) {
       this.alarmname = alarmname;
       this.systems = systems;
       this.tt = tt;
       this.types = types;
       this.alarm = alarm;
       this.regtime = regtime;
       this.status = status;
       this.severity = severity;
       this.details = details;
       this.originatetime = originatetime;
       this.cleartime = cleartime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Alarmname getAlarmname() {
        return this.alarmname;
    }
    
    public void setAlarmname(Alarmname alarmname) {
        this.alarmname = alarmname;
    }
    public Systems getSystems() {
        return this.systems;
    }
    
    public void setSystems(Systems systems) {
        this.systems = systems;
    }
    public Tt getTt() {
        return this.tt;
    }
    
    public void setTt(Tt tt) {
        this.tt = tt;
    }
    public Types getTypes() {
        return this.types;
    }
    
    public void setTypes(Types types) {
        this.types = types;
    }
    public String getAlarm() {
        return this.alarm;
    }
    
    public void setAlarm(String alarm) {
        this.alarm = alarm;
    }
    public Date getRegtime() {
        return this.regtime;
    }
    
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Integer getSeverity() {
        return this.severity;
    }
    
    public void setSeverity(Integer severity) {
        this.severity = severity;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }
    public Date getOriginatetime() {
        return this.originatetime;
    }
    
    public void setOriginatetime(Date originatetime) {
        this.originatetime = originatetime;
    }
    public Date getCleartime() {
        return this.cleartime;
    }
    
    public void setCleartime(Date cleartime) {
        this.cleartime = cleartime;
    }




}


