package model;
// Generated Aug 29, 2017 2:09:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String addressLine1;
     private String addressLine2;
     private String addressLine3;
     private String email;
     private String telephone;
     private String fax;
     private Integer status;
     private Set systemses = new HashSet(0);
     private Set tts = new HashSet(0);
     private Set departments = new HashSet(0);
     private Set users = new HashSet(0);

    public Company() {
    }

	
    public Company(String addressLine2, String addressLine3, String email, String telephone, String fax) {
        this.addressLine2 = addressLine2;
        this.addressLine3 = addressLine3;
        this.email = email;
        this.telephone = telephone;
        this.fax = fax;
    }
    public Company(String name, String addressLine1, String addressLine2, String addressLine3, String email, String telephone, String fax, Integer status, Set systemses, Set tts, Set departments, Set users) {
       this.name = name;
       this.addressLine1 = addressLine1;
       this.addressLine2 = addressLine2;
       this.addressLine3 = addressLine3;
       this.email = email;
       this.telephone = telephone;
       this.fax = fax;
       this.status = status;
       this.systemses = systemses;
       this.tts = tts;
       this.departments = departments;
       this.users = users;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddressLine1() {
        return this.addressLine1;
    }
    
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }
    public String getAddressLine2() {
        return this.addressLine2;
    }
    
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }
    public String getAddressLine3() {
        return this.addressLine3;
    }
    
    public void setAddressLine3(String addressLine3) {
        this.addressLine3 = addressLine3;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getSystemses() {
        return this.systemses;
    }
    
    public void setSystemses(Set systemses) {
        this.systemses = systemses;
    }
    public Set getTts() {
        return this.tts;
    }
    
    public void setTts(Set tts) {
        this.tts = tts;
    }
    public Set getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Set departments) {
        this.departments = departments;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


