package model;
// Generated Aug 29, 2017 2:09:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PersonType generated by hbm2java
 */
public class PersonType  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Integer status;
     private Set users = new HashSet(0);

    public PersonType() {
    }

    public PersonType(String name, Integer status, Set users) {
       this.name = name;
       this.status = status;
       this.users = users;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


