package model;
// Generated Aug 29, 2017 2:09:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SystemsHasParameters generated by hbm2java
 */
public class SystemsHasParameters  implements java.io.Serializable {


     private Integer id;
     private Parameters parameters;
     private Systems systems;
     private Integer status;
     private Set periodics = new HashSet(0);

    public SystemsHasParameters() {
    }

	
    public SystemsHasParameters(Parameters parameters, Systems systems) {
        this.parameters = parameters;
        this.systems = systems;
    }
    public SystemsHasParameters(Parameters parameters, Systems systems, Integer status, Set periodics) {
       this.parameters = parameters;
       this.systems = systems;
       this.status = status;
       this.periodics = periodics;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Parameters getParameters() {
        return this.parameters;
    }
    
    public void setParameters(Parameters parameters) {
        this.parameters = parameters;
    }
    public Systems getSystems() {
        return this.systems;
    }
    
    public void setSystems(Systems systems) {
        this.systems = systems;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getPeriodics() {
        return this.periodics;
    }
    
    public void setPeriodics(Set periodics) {
        this.periodics = periodics;
    }




}


