package model;
// Generated Aug 29, 2017 2:09:57 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TtUpdate generated by hbm2java
 */
public class TtUpdate  implements java.io.Serializable {


     private Integer id;
     private Tt tt;
     private User user;
     private String comment;
     private Date regtime;
     private Integer status;
     private String info;
     private Set alertses = new HashSet(0);

    public TtUpdate() {
    }

	
    public TtUpdate(Tt tt, User user) {
        this.tt = tt;
        this.user = user;
    }
    public TtUpdate(Tt tt, User user, String comment, Date regtime, Integer status, String info, Set alertses) {
       this.tt = tt;
       this.user = user;
       this.comment = comment;
       this.regtime = regtime;
       this.status = status;
       this.info = info;
       this.alertses = alertses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tt getTt() {
        return this.tt;
    }
    
    public void setTt(Tt tt) {
        this.tt = tt;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Date getRegtime() {
        return this.regtime;
    }
    
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }
    public Set getAlertses() {
        return this.alertses;
    }
    
    public void setAlertses(Set alertses) {
        this.alertses = alertses;
    }




}


