package model;
// Generated Aug 29, 2017 2:09:57 PM by Hibernate Tools 4.3.1



/**
 * UserHasDepartment generated by hbm2java
 */
public class UserHasDepartment  implements java.io.Serializable {


     private Integer id;
     private Department department;
     private User user;
     private String description;
     private Integer status;

    public UserHasDepartment() {
    }

	
    public UserHasDepartment(Department department, User user) {
        this.department = department;
        this.user = user;
    }
    public UserHasDepartment(Department department, User user, String description, Integer status) {
       this.department = department;
       this.user = user;
       this.description = description;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


